import { createConfig } from "wagmi"
import {
  arbitrum,
  base,
  bitkub,
  celo,
  gnosis,
  hedera,
  kinto,
  linea,
  mainnet,
  mantle,
  polygon,
  scroll,
  sepolia,
  worldchain,
  zircuit,
} from "viem/chains"
import { http } from "viem"

export const wagmiConfig = createConfig({
  multiInjectedProviderDiscovery: false,
  chains: [
    sepolia,
    mainnet,
    polygon,
    // flow,
    bitkub,
    kinto,
    worldchain,
    arbitrum,
    scroll,
    mantle,
    gnosis,
    hedera,
    celo,
    base,
    zircuit,
    linea,
  ],
  transports: {
    [sepolia.id]: http(),
    [mainnet.id]: http(),
    [polygon.id]: http(),
    // [flow.id]: http(),
    [bitkub.id]: http(),
    [kinto.id]: http(),
    [worldchain.id]: http(),
    [arbitrum.id]: http(),
    [scroll.id]: http(),
    [mantle.id]: http(),
    [gnosis.id]: http(),
    [hedera.id]: http(),
    [celo.id]: http(),
    [base.id]: http(),
    [zircuit.id]: http(),
    [linea.id]: http(),
  },
})
