import { createConfig } from "wagmi"
import {
  sepolia,
  polygonAmoy,
  arbitrumSepolia,
  baseSepolia,
  celoAlfajores,
  scrollSepolia,
  hederaTestnet,
  flowTestnet,
  mantleTestnet,
  neonDevnet,
  linea,

  // arbitrum,
  // base,
  // bitkub,
  // celo,
  // gnosis,
  // hedera,
  // kinto,
  // linea,
  // mainnet,
  // mantle,
  // polygon,
  // scroll,
  // worldchain,
  // zircuit,
} from "viem/chains"
import { http } from "viem"

export const wagmiConfig = createConfig({
  multiInjectedProviderDiscovery: false,
  chains: [
    sepolia,
    polygonAmoy,
    arbitrumSepolia,
    baseSepolia,
    celoAlfajores,
    scrollSepolia,
    hederaTestnet,
    flowTestnet,
    mantleTestnet,
    neonDevnet,
    linea,
  ],
  transports: {
    [sepolia.id]: http(),
    [polygonAmoy.id]: http(),
    [arbitrumSepolia.id]: http(),
    [baseSepolia.id]: http(),
    [celoAlfajores.id]: http(),
    [scrollSepolia.id]: http(),
    [hederaTestnet.id]: http(),
    [flowTestnet.id]: http(),
    [mantleTestnet.id]: http(),
    [neonDevnet.id]: http(),
    [linea.id]: http(),
  },
})
